### PR TITLE
Update AlphaRatio.tracker

### PR DESCRIPTION
**Pull request by pdx0**
updated .tracker to match new announce line
related issue #211

### CODE REVIEW

**Comment by pdx0** [comment]
related issue #211

**Comment by thebigmunch** [comment]
So, this should actually be done using multilinepatterns (see [BTN](https://github.com/autodl-community/autodl-trackers/blob/master/BTN.tracker) to capture both lines so we don't lose any filter options like pretime. I can take a look at it some time if you are unable to do that.

**Comment by pdx0** [comment]
i just assumed (oops) that the old line was kept not to break things, will update for multiline

**Comment by phiend7** [comment]
@pdx0 
[https://www.dropbox.com/s/p2tm6ijtp3mz88x/AlphaRatio.tracker?dl=0](url)
So far, I have tested extensively with no problems.

**Pull request closed without merging**
