### PR TITLE
update the server name for HDCenter

### PR DESCRIPTION
**Pull request by pyed**

### CODE REVIEW

**Comment by thebigmunch** [comment]
Besides not conforming to the contributing guidelines, irc.hdcenter.cc redirects to irc.fastshit.net. There shouldn't be a reason to change it unless the tracker themselves say to use irc.fastshit.net instead.

**Comment by pyed** [comment]
Autodl wasn't matching anything because of the server name, I had to change it so autodl will start matching

**Comment by thebigmunch** [comment]
autodl-irssi checks both the server address and network name, but only requires that one of them match. This worked fine for the person who requested the tracker, and a number of other trackers work in the same situation. Is anyone else on the tracker having trouble with it?

**Comment by pyed** [comment]
I'm not sure, what I'm sure of is that I spent the last two days trying to figure out why autodl not matching anything from hdc, after reading the .tracker file carefully, I noticed that the server name is different, after fixing that, autodl started to work as expected

**Pull request closed without merging**
