### PR TITLE
Additions to GazelleGames.tracker

### PR DESCRIPTION
**Pull request by ElectronicMonolith**
Added support for variables: category, tags, freeleech, origin

Kept the original filter mostly intact. Just removed a redundant space before torrentName capture.
Don't want to be too strict with the first capture.
The new variables are filtered from torrentName as this should help with any other weird announces. 

Any suggestions are welcome

Related issue: #151 Add Category Information to GazelleGames

### CODE REVIEW

**Comment by Scrxtchy** [comment]
But everything on #announce is freeleech for 6 hours

**Comment by ElectronicMonolith** [comment]
I provided an example of a freeleech announce.

**Comment by thebigmunch** [comment]
Well, beside the commit messages not conforming to the guidelines (verb tense and no mention of the tracker)...

As I stated in the issue about categories, I really don't want to add any special cases if I don't have to. Has anyone talked to the tracker about separating it out? Parentheses are put around the release tags. While not being very good, that would be something to at least consider for the category. All-in-all, their announce format is terrible for human parsing and kinda clunky for computer parsing. Not sure why so many trackers fail so hard at this. The number of overlapping extracts used in its current state is kinda absurd.

As is, freeleech should probably be captured at the end with yet another extract. But that should also just be done more sanely in the announce.

Seriously, this announce format just needs to be made not terrible.

**Comment by ElectronicMonolith** [comment]
I can ask them but honestly...it's been over two years and the format has stayed nearly the same. I'll suggest separation of category at the very least.

Regarding my commits. Sorry about that....I'm still pretty new to github. For some reason I thought it was something the maintainer could squash/rename.

**Pull request closed without merging**
